yarnPath: .yarn/releases/yarn-3.2.0.cjs
nodeLinker: node-modules

# By default, publish packages privately to GitHub for internal testing instead of to NPM.
npmScopes:
  unflakable:
    npmPublishRegistry: https://npm.pkg.github.com
npmPublishAccess: restricted
