yarnPath: .yarn/releases/yarn-3.5.1.cjs
nodeLinker: node-modules

# By default, publish packages privately to GitHub for internal testing instead of to NPM.
npmScopes:
  unflakable-private:
    npmPublishRegistry: https://npm.pkg.github.com
npmPublishAccess: restricted
