name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, unsquashed-private ]
  pull_request:
    branches: [ main, unsquashed-private ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: { }

jobs:
  check:
    name: Typecheck, lint, and audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: yarn

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}

      - id: install
        run: yarn install --immutable

      - run: yarn build

      - if: ${{ always() && steps.install.outcome == 'success' }}
        run: yarn lint

      - if: ${{ always() && steps.install.outcome == 'success' }}
        run: yarn prettier:check

      - if: ${{ always() && steps.install.outcome == 'success' }}
        run: yarn audit

  jest_integration_tests:
    name: "Jest Integration Tests: Jest ${{ matrix.jest }} + Node ${{ matrix.node }}"
    runs-on: ubuntu-latest
    needs:
      # Don't incur the cost of the test matrix if the basic build fails.
      - check
    strategy:
      fail-fast: false
      matrix:
        node:
          - 14
          - 16
          - 18
        jest:
          - "27.5"
          - "27.4"
          - "27.3"
          - "27.2"
          - "27.1"
          - "27.0"
          - "26.6"
          - "26.5"
          - "26.4"
          - "26.3"
          - "26.2"
          - "26.1"
          - "26.0"
          - "25.5"
          - "25.4"
          - "25.3"
          - "25.2"
          - "25.1"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node${{ matrix.node }}-jest${{ matrix.jest }}-modules-${{ hashFiles('yarn.lock') }}

      - id: install
        run: yarn install --immutable

      # Since Jest is composed of many packages, we need to make sure that they're all using the
      # same major and minor versions. Otherwise, NPM will keep the newer minor versions since
      # they're semver-compatible. This script iteratively installs the lowest compatible semver
      # version for each package until yarn.lock converges. See the script for some edge cases due
      # to missing package versions with certain minor version numbers.
      - name: Set Jest version
        run: |
          yarn set-jest-version ${{ matrix.jest }}
          grep --after-context=1 "^\".*jest.*" yarn.lock

      - name: Set resolution for chalk to 3.0.0
        if: ${{ startsWith(matrix.jest, '25.')  }}
        run: yarn set resolution "chalk@npm:^3.0.0 || ^4.0.0" 3.0

      - run: yarn build

      - name: Enable Unflakable dogfooding
        run: |
          echo "UNFLAKABLE_API_KEY=${{ secrets.UNFLAKABLE_API_KEY }}" >> $GITHUB_ENV
          echo "UNFLAKABLE_ENABLED=true" >> $GITHUB_ENV
        if: github.event.action != 'pull_request'

      - working-directory: packages/jest-plugin/test/integration
        env:
          DEBUG: unflakable:*
        run: |
          if [ "${{ github.repository }}" == "unflakable/unflakable-javascript" ]; then
            export UNFLAKABLE_SUITE_ID=29KWCuK12VnU7pkpvWgrGS0woAX
          else
            export UNFLAKABLE_SUITE_ID=28UidZ8cSKjRe4g1xkd9EE8noDF
          fi
          yarn test
